#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Enable BP4O
autoload -Uz bp4o
bp4o

# Aliases
alias vi='nvim'
alias vim='nvim'
alias nv='nvim'
alias oldvim='vim'
alias viconf='nvim ~/.config/nvim/init.vim'

alias fcp='/bin/cp -f'
alias ls="${aliases[ls]:-ls} -FG"
alias l='ls'
alias la='ls -A'
alias ll='ls -lh'
alias lla='ll -A'
alias tm='tmux -2'
alias grep="rg"

unsetopt CORRECT

# Local things
if [ -f ~/.localrc ]; then
  source ~/.localrc
fi
