#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Aliases
alias vi='vim'
alias nv='nvim'

alias fcp='/bin/cp -f'
alias ls="${aliases[ls]:-ls} -FG"
alias l='ls'
alias la='ls -A'
alias ll='ls -lh'
alias lla='ll -A'

# Local things
if [ -f ~/.localrc ]; then
  source ~/.localrc
fi
