#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Aliases
alias yum='sudo yum'
alias pip='sudo pip'

# Cisco things
if [ -f ~/.ciscorc ]; then
    . ~/.ciscorc
fi

# Android Studio
export JAVA_HOME=/usr/java/latest
export ANDROID_HOME=/opt/android-studio/sdk
PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

# Perforce
export P4CONFIG=.p4config
export P4IGNORE=.p4ignore
export P4EDITOR=vim
export P4DIFF=vimdiff

# Python
function pyenv {
    source /usr/bin/virtualenvwrapper.sh
}
